import { StyleSheet } from 'react-native';
import { MUSIC_HOME_THEME as C } from '../../theme/musicHomeTheme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 128,
  },
  header: {
    paddingTop: 40,
    paddingBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontSize: 40,
    color: '#e8e2f8',
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  headerSubtitle: {
    marginTop: 4,
    color: C.textDim,
    fontSize: 12,
  },
  headerAction: {
    width: 64,
    height: 64,
    borderRadius: 32,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: C.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#271a46',
    alignSelf: 'center',
    marginLeft: 12,
  },
  profilePlaceholder: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#3b1f6e',
    borderWidth: 1,
    borderColor: C.accent,
  },
  profileImage: {
    width: 64,
    height: 64,
  },
  profileInitial: {
    color: '#f0eaff',
    fontSize: 24,
    fontWeight: '700',
  },
  bentoGrid: {
    marginBottom: 20,
  },
  bentoSectionTitle: {
    color: C.text,
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 12,
  },
  bentoEmpty: {
    padding: 24,
    backgroundColor: C.bgCard,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: 'center',
  },
  bentoEmptyText: {
    color: C.textMute,
    fontSize: 14,
  },
  bentoRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  bentoCard: {
    backgroundColor: C.bgCard,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    padding: 14,
  },
  bentoCardLarge: {
    marginBottom: 8,
  },
  bentoCardMedium: {
    flex: 1,
  },
  bentoCardWide: {
    marginBottom: 8,
  },
  bentoTitle: {
    color: C.text,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 4,
  },
  bentoSubtitle: {
    color: C.accentFg,
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 16,
  },
  bentoSubtitleCentered: {
    color: C.accentFg,
    fontSize: 12,
    fontWeight: '600',
    marginTop: 12,
    textAlign: 'center',
  },
  barChartContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    height: 80,
    paddingTop: 8,
  },
  barCol: {
    alignItems: 'center',
    flex: 1,
  },
  barTrack: {
    width: 24,
    height: 60,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 4,
    justifyContent: 'flex-end',
    overflow: 'hidden',
    marginBottom: 6,
  },
  barFill: {
    width: '100%',
    backgroundColor: C.accent,
    borderRadius: 4,
  },
  barLabel: {
    color: C.textMute,
    fontSize: 10,
  },
  storageDonutContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 60,
    marginTop: 8,
  },
  storageDonutOuter: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    justifyContent: 'flex-end',
    overflow: 'hidden',
    position: 'relative',
  },
  storageDonutFill: {
    width: '100%',
    backgroundColor: C.accent,
  },
  storageDonutHole: {
    position: 'absolute',
    top: 10,
    left: 10,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: C.bgCard,
  },
  topArtistContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
  },
  topArtistName: {
    color: C.text,
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 4,
  },
  topArtistPlays: {
    color: C.textMute,
    fontSize: 12,
  },
  weeklyHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  bentoSubtitleInline: {
    color: C.accentFg,
    fontSize: 12,
    fontWeight: '600',
  },
  bentoPlaceholder: {
    color: C.textMute,
    fontSize: 12,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  mostPlayedContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
  },
  mostPlayedArtworkLarge: {
    width: 64,
    height: 64,
    borderRadius: 8,
    marginBottom: 8,
  },
  mostPlayedArtworkFallbackLarge: {
    width: 64,
    height: 64,
    borderRadius: 8,
    backgroundColor: '#2a1b49',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  mostPlayedTitle: {
    color: C.text,
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 4,
  },
  mostPlayedArtist: {
    color: C.textMute,
    fontSize: 12,
    textAlign: 'center',
    marginTop: 2,
  },
  syncBanner: {
    marginBottom: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    backgroundColor: C.bgCard,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  syncBannerText: {
    marginLeft: 8,
    color: C.accentFg,
    fontSize: 12,
    fontWeight: '700',
  },
  quickActionsRow: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  quickActionCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.bgCard,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickActionGap: {
    marginRight: 8,
  },
  quickActionLabel: {
    marginLeft: 8,
    color: C.text,
    fontSize: 13,
    fontWeight: '700',
  },
  sectionRow: {
    marginTop: 12,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: C.textDim,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  sectionAction: {
    color: C.accentFg,
    fontSize: 12,
    fontWeight: '600',
  },
  playlistsListWrap: {
    height: 132,
    width: '100%',
  },
  playlistsRow: {
    paddingTop: 2,
    paddingBottom: 4,
    paddingRight: 2,
  },
  playlistCard: {
    width: 102,
    height: 124,
    marginRight: 10,
  },
  playlistArt: {
    width: '100%',
    height: 94,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  playlistEmoji: {
    fontSize: 30,
    color: '#f0eaff',
    fontWeight: '700',
  },
  playlistName: {
    marginTop: 6,
    color: '#bdb5d8',
    fontSize: 11,
    fontWeight: '700',
  },
  playlistCount: {
    marginTop: 2,
    color: C.textMute,
    fontSize: 10,
  },
  songCard: {
    marginBottom: 9,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: C.bgCard,
    flexDirection: 'row',
    alignItems: 'center',
  },
  songMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 60,
  },
  songArtwork: {
    width: 60,
    height: 60,
  },
  songArtworkFallback: {
    width: 60,
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2a1b49',
  },
  songMeta: {
    flex: 1,
    minHeight: 60,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  songTitle: {
    color: C.text,
    fontSize: 14,
    fontWeight: '700',
  },
  songArtist: {
    marginTop: 3,
    color: C.textMute,
    fontSize: 11,
  },
  favoriteButton: {
    width: 42,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 60,
  },
  emptyContainer: {
    paddingTop: 64,
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  emptyTitle: {
    marginTop: 12,
    color: '#f0eaff',
    fontSize: 19,
    fontWeight: '700',
  },
  emptySubtitle: {
    marginTop: 8,
    color: C.textDim,
    fontSize: 13,
    textAlign: 'center',
  },
});

export default styles;
