import {StyleSheet} from 'react-native';
import {MUSIC_HOME_THEME as C} from '../../theme/musicHomeTheme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },
  topBar: {
    paddingTop: 40,
    paddingHorizontal: 16,
    paddingBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: C.borderDim,
    backgroundColor: C.bg,
  },
  brand: {
    fontSize: 40,
    color: '#e8e2f8',
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  settingsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 7,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#1e1445',
  },
  settingsValue: {
    color: C.accentFg,
    fontWeight: '600',
    fontSize: 13,
    marginHorizontal: 6,
  },
  downloaderTabsRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: C.borderDim,
    paddingHorizontal: 16,
    backgroundColor: C.bg,
  },
  downloaderTabButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 11,
    position: 'relative',
  },
  downloaderTabLabelWrap: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  downloaderTabText: {
    color: C.textMute,
    fontSize: 18,
    fontWeight: '500',
  },
  downloaderTabTextActive: {
    color: C.text,
    fontWeight: '700',
  },
  downloaderTabUnderline: {
    position: 'absolute',
    bottom: -1,
    left: '20%',
    right: '20%',
    height: 2,
    backgroundColor: C.accent,
  },
  queueBadge: {
    marginLeft: 6,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: C.accent,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  queueBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  searchPanel: {
    flex: 1,
    minHeight: 0,
  },
  searchControlsSection: {
    paddingBottom: 10,
  },
  searchTop: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 10,
  },
  searchControlsDivider: {
    marginHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: C.borderDim,
  },
  searchInputWrap: {
    minHeight: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.bgCard,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchInput: {
    flex: 1,
    color: C.text,
    fontSize: 14,
    paddingVertical: 0,
    paddingHorizontal: 8,
  },
  searchActionButton: {
    width: 30,
    height: 30,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: '#1e1445',
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchActionButtonDisabled: {
    opacity: 0.6,
  },
  searchTypeRow: {
    flexDirection: 'row',
    marginTop: 12,
  },
  searchTypeButton: {
    flex: 1,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: C.border,
    paddingVertical: 8,
    backgroundColor: C.bgCard,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchTypeButtonGap: {
    marginRight: 6,
  },
  searchTypeButtonActive: {
    borderColor: C.accent,
    backgroundColor: C.accent,
  },
  searchTypeText: {
    color: C.textMute,
    fontSize: 13,
    fontWeight: '600',
  },
  searchTypeTextActive: {
    color: '#fff',
    fontWeight: '600',
  },
  searchResultsList: {
    flex: 1,
    minHeight: 0,
  },
  searchListContent: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 180,
  },
  searchListContentEmpty: {
    flexGrow: 1,
  },
  albumHeaderCard: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.bgCard,
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginBottom: 10,
  },
  albumHeaderTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  albumBackButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  albumBackText: {
    marginLeft: 5,
    color: C.textDim,
    fontSize: 12,
    fontWeight: '600',
  },
  albumQueueAllButton: {
    minHeight: 30,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: C.accent,
    backgroundColor: '#1e1445',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  albumQueueAllButtonDisabled: {
    opacity: 0.55,
  },
  albumQueueAllText: {
    marginLeft: 6,
    color: C.accentFg,
    fontSize: 12,
    fontWeight: '700',
  },
  albumHeaderTitle: {
    color: C.text,
    fontSize: 15,
    fontWeight: '700',
  },
  albumHeaderMeta: {
    marginTop: 3,
    color: C.textMute,
    fontSize: 12,
  },
  albumTracksEmptyWrap: {
    alignItems: 'center',
    paddingTop: 26,
    paddingBottom: 14,
  },
  albumTracksLoadingText: {
    marginTop: 10,
    color: C.textMute,
    fontSize: 12,
  },
  resultCard: {
    flexDirection: 'row',
    alignItems: 'stretch',
    minHeight: 64,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.bgCard,
    overflow: 'hidden',
    marginBottom: 8,
  },
  resultArtworkShell: {
    width: 64,
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultArtworkImage: {
    width: 64,
    height: 64,
  },
  resultInfo: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  resultTitle: {
    color: C.text,
    fontSize: 14,
    fontWeight: '700',
  },
  resultArtist: {
    color: C.textMute,
    fontSize: 12,
    marginTop: 2,
  },
  resultMeta: {
    color: C.textDeep,
    fontSize: 11,
    marginTop: 2,
  },
  resultRight: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: 10,
  },
  resultDuration: {
    color: C.textDeep,
    fontSize: 11,
    marginRight: 8,
    minWidth: 40,
    textAlign: 'right',
  },
  downloadButton: {
    width: 30,
    height: 30,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: C.accent,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.accent,
  },
  downloadButtonBusy: {
    opacity: 0.7,
  },
  downloadButtonDone: {
    backgroundColor: C.border,
    borderColor: C.textDeep,
  },
  downloadButtonRetry: {
    borderColor: '#7b3146',
    backgroundColor: '#2a1430',
  },
  queueListContent: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 180,
  },
  queueCardShell: {
    marginBottom: 8,
  },
  queueCard: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'stretch',
    position: 'relative',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.bgCard,
    overflow: 'hidden',
  },
  queueCardFailed: {
    borderColor: '#4a1a1a',
  },
  queueAccent: {
    width: 4,
  },
  queueArtworkWrap: {
    width: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
  queueArtwork: {
    width: 64,
    height: 64,
  },
  queueInfo: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  queueHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  queueTitle: {
    flex: 1,
    color: C.text,
    fontSize: 14,
    fontWeight: '700',
    marginRight: 6,
  },
  queueStatus: {
    fontSize: 11,
    fontWeight: '700',
  },
  queueProgressTrack: {
    height: 3,
    borderRadius: 1,
    backgroundColor: C.border,
    overflow: 'hidden',
  },
  queueProgressFill: {
    height: '100%',
    borderRadius: 1,
  },
  queueMeta: {
    color: C.textDeep,
    fontSize: 11,
    marginTop: 4,
  },
  queueActionWrap: {
    width: 44,
    alignItems: 'center',
    justifyContent: 'center',
    paddingRight: 10,
  },
  queueActionSpacer: {
    width: 30,
  },
  retrySquareButton: {
    width: 30,
    height: 30,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: '#1e0d3a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  retrySquareButtonBusy: {
    opacity: 0.8,
  },
  cancelSquareButton: {
    width: 30,
    height: 30,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: C.borderDim,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelSquareButtonBusy: {
    opacity: 0.75,
  },
  queueDoneState: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  queueDoneOutlineOverlay: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 8,
    overflow: 'hidden',
    zIndex: 6,
  },
  queueDoneOutlineLine: {
    position: 'absolute',
    backgroundColor: '#22c55e',
  },
  queueDoneOutlineTop: {
    left: 0,
    top: 0,
    height: 2,
  },
  queueDoneOutlineRight: {
    right: 0,
    top: 0,
    width: 2,
  },
  queueDoneOutlineBottom: {
    right: 0,
    bottom: 0,
    height: 2,
  },
  queueDoneOutlineLeft: {
    left: 0,
    bottom: 0,
    width: 2,
  },
  emptyContainer: {
    paddingTop: 90,
    paddingHorizontal: 24,
    alignItems: 'center',
  },
  emptyIcon: {
    marginBottom: 8,
  },
  emptyTitle: {
    color: C.textDeep,
    fontSize: 20,
    fontWeight: '700',
  },
  emptySubtitle: {
    marginTop: 8,
    color: C.textMute,
    fontSize: 13,
    textAlign: 'center',
  },
  hiddenWebView: {
    position: 'absolute',
    width: 1,
    height: 1,
    opacity: 0,
    left: -9999,
    top: -9999,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(8, 5, 18, 0.45)',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    paddingTop: 94,
    paddingHorizontal: 16,
  },
  modalCard: {
    minWidth: 170,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.bgCard,
    paddingVertical: 6,
    paddingHorizontal: 0,
  },
  modalTitle: {
    color: C.textDim,
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    paddingHorizontal: 12,
    paddingBottom: 5,
  },
  optionRow: {
    backgroundColor: C.bgCard,
    paddingVertical: 8,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  optionRowSelected: {
    backgroundColor: '#211840',
  },
  optionTextWrap: {
    flex: 1,
    paddingRight: 8,
  },
  optionTitle: {
    color: C.text,
    fontSize: 11,
    fontWeight: '600',
  },
  optionSubtitle: {
    color: C.textMute,
    fontSize: 10,
    marginTop: 1,
  },
});

export default styles;
