import {StyleSheet} from 'react-native';
import {MUSIC_HOME_THEME as C} from '../../theme/musicHomeTheme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },
  contentContainer: {
    paddingTop: 32,
    paddingHorizontal: 16,
    paddingBottom: 128,
  },
  header: {
    marginBottom: 4,
  },
  headerTitle: {
    fontSize: 38,
    color: '#e8e2f8',
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  headerSubtitle: {
    marginTop: 4,
    color: C.textDim,
    fontSize: 12,
  },
  sectionWrap: {
    marginTop: 14,
  },
  sectionLabel: {
    marginBottom: 7,
    color: C.textDim,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  sectionCard: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: C.bgCard,
  },
  settingsRow: {
    minHeight: 62,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingsRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: C.borderDim,
  },
  settingsRowDisabled: {
    opacity: 0.7,
  },
  settingsRowLeft: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  settingsRowIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: '#1f143a',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  settingsRowTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  settingsRowTitle: {
    color: C.text,
    fontSize: 13,
    fontWeight: '700',
  },
  settingsRowSubtitle: {
    marginTop: 2,
    color: C.textMute,
    fontSize: 11,
  },
  settingsRowRight: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 10,
  },
  changeButton: {
    paddingVertical: 4,
    paddingHorizontal: 6,
    marginRight: 2,
  },
  changeButtonText: {
    color: C.accentFg,
    fontSize: 12,
    fontWeight: '700',
  },
  inlineInputWrap: {
    borderTopWidth: 1,
    borderTopColor: C.borderDim,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  inlineInput: {
    flex: 1,
    minHeight: 36,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 7,
    backgroundColor: C.bg,
    color: C.text,
    paddingHorizontal: 10,
    fontSize: 12,
  },
  inlineSaveButton: {
    marginLeft: 8,
    minHeight: 36,
    borderWidth: 1,
    borderColor: C.accent,
    borderRadius: 7,
    backgroundColor: C.accent,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  inlineSaveButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  profileCard: {
    minHeight: 98,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    backgroundColor: C.bgCard,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: '#271a46',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarImage: {
    width: 64,
    height: 64,
  },
  avatarFallbackWrap: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarFallbackEmoji: {
    fontSize: 29,
  },
  avatarOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.08)',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    paddingRight: 4,
    paddingBottom: 4,
  },
  avatarOverlayIconWrap: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileMetaWrap: {
    flex: 1,
    minWidth: 0,
    marginLeft: 12,
  },
  profileNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileNameText: {
    flex: 1,
    color: C.text,
    fontSize: 18,
    fontWeight: '700',
  },
  profileEditButton: {
    width: 28,
    height: 28,
    marginLeft: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1f143a',
  },
  profileNameInput: {
    minHeight: 36,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 7,
    backgroundColor: C.bg,
    color: C.text,
    paddingHorizontal: 10,
    fontSize: 16,
    fontWeight: '700',
  },
  profileHint: {
    marginTop: 6,
    color: C.textMute,
    fontSize: 11,
  },
  crossfadeExpandWrap: {
    overflow: 'hidden',
    borderBottomColor: C.borderDim,
  },
  crossfadeExpandWrapOpen: {
    borderBottomWidth: 1,
  },
  crossfadeExpandWrapClosed: {
    borderBottomWidth: 0,
  },
  crossfadeExpandContent: {
    height: 56,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  crossfadeSlider: {
    flex: 1,
    marginRight: 10,
  },
  crossfadeDurationText: {
    width: 30,
    textAlign: 'right',
    color: C.accentFg,
    fontSize: 12,
    fontWeight: '700',
  },
  storageUsageDropdown: {
    borderTopWidth: 1,
    borderTopColor: C.borderDim,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#140d2a',
  },
  storageUsageLoadingWrap: {
    minHeight: 30,
    flexDirection: 'row',
    alignItems: 'center',
  },
  storageUsageLoadingText: {
    marginLeft: 8,
    color: C.textMute,
    fontSize: 11,
  },
  storageUsageErrorText: {
    color: '#fca5a5',
    fontSize: 11,
  },
  storageUsageEmptyText: {
    color: C.textMute,
    fontSize: 11,
  },
  storageUsageItem: {
    marginTop: 10,
  },
  storageUsageItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  storageUsageFormatText: {
    color: C.text,
    fontSize: 12,
    fontWeight: '700',
  },
  storageUsageItemMetaText: {
    color: C.textMute,
    fontSize: 11,
    marginLeft: 12,
  },
  storageUsageBarTrack: {
    marginTop: 6,
    height: 6,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: '#2a1d49',
  },
  storageUsageBarFill: {
    height: '100%',
    borderRadius: 999,
  },
  privacyPolicyDropdown: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#140d2a',
  },
  privacyPolicyIntro: {
    color: C.textMute,
    fontSize: 11,
    lineHeight: 16,
  },
  privacyPolicyLastUpdated: {
    marginTop: 6,
    color: C.textDeep,
    fontSize: 10,
    fontWeight: '600',
  },
  privacyPolicyItem: {
    marginTop: 10,
  },
  privacyPolicyItemHeading: {
    color: C.text,
    fontSize: 12,
    fontWeight: '700',
  },
  privacyPolicyItemDetails: {
    marginTop: 3,
    color: C.textMute,
    fontSize: 11,
    lineHeight: 16,
  },
});

export default styles;
