import {StyleSheet} from 'react-native';
import {MUSIC_HOME_THEME as C} from '../../theme/musicHomeTheme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 40,
  },
  topBar: {
    paddingTop: 54,
    paddingBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.bgCard,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topBarTitle: {
    color: C.text,
    fontSize: 14,
    fontWeight: '700',
  },
  topBarSpacer: {
    width: 32,
  },
  heroSection: {
    alignItems: 'center',
    paddingBottom: 14,
  },
  heroArtworkWrap: {
    marginBottom: 14,
  },
  artworkGrid: {
    width: 180,
    height: 180,
    flexDirection: 'row',
    flexWrap: 'wrap',
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: C.border,
  },
  gridImage: {
    width: 90,
    height: 90,
  },
  gridImageEmpty: {
    width: 90,
    height: 90,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2a1b49',
  },
  placeholderArtwork: {
    width: 180,
    height: 180,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2a1b49',
  },
  playlistName: {
    color: '#f0eaff',
    fontSize: 28,
    fontWeight: '800',
    textAlign: 'center',
  },
  playlistDescription: {
    marginTop: 6,
    color: C.textDim,
    fontSize: 12,
    textAlign: 'center',
    paddingHorizontal: 14,
  },
  playlistInfo: {
    marginTop: 7,
    color: C.textMute,
    fontSize: 12,
  },
  playAllButton: {
    marginTop: 12,
    borderRadius: 7,
    backgroundColor: C.accent,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 9,
    paddingHorizontal: 14,
  },
  playAllDisabled: {
    opacity: 0.5,
  },
  playAllText: {
    marginLeft: 4,
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  heroActions: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  addTracksButton: {
    marginTop: 12,
    marginLeft: 8,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.bgCard,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 9,
    paddingHorizontal: 14,
  },
  addTracksText: {
    marginLeft: 4,
    color: C.accentFg,
    fontSize: 12,
    fontWeight: '700',
  },
  sectionLabel: {
    marginTop: 6,
    marginBottom: 8,
    color: C.textDim,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  songCard: {
    marginBottom: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.bgCard,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
  },
  songMain: {
    flex: 1,
    minHeight: 60,
    flexDirection: 'row',
    alignItems: 'center',
  },
  songIndex: {
    width: 30,
    color: C.textDeep,
    fontSize: 12,
    textAlign: 'center',
    fontWeight: '700',
  },
  songArtwork: {
    width: 46,
    height: 46,
    borderRadius: 6,
  },
  songArtworkFallback: {
    width: 46,
    height: 46,
    borderRadius: 6,
    backgroundColor: '#2a1b49',
    alignItems: 'center',
    justifyContent: 'center',
  },
  songMeta: {
    flex: 1,
    paddingHorizontal: 10,
  },
  songTitle: {
    color: C.text,
    fontSize: 14,
    fontWeight: '700',
  },
  songArtist: {
    marginTop: 3,
    color: C.textMute,
    fontSize: 11,
  },
  removeBtn: {
    width: 36,
    minHeight: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyContainer: {
    paddingTop: 60,
    alignItems: 'center',
  },
  emptyTitle: {
    marginTop: 12,
    color: '#f0eaff',
    fontSize: 18,
    fontWeight: '700',
  },
  emptySubtitle: {
    marginTop: 7,
    color: C.textDim,
    fontSize: 13,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: C.modalOverlayBg,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  modalCard: {
    width: '100%',
    maxHeight: '82%',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.bgCard,
    padding: 14,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  modalTitle: {
    color: C.text,
    fontSize: 20,
    fontWeight: '700',
  },
  modalInput: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    backgroundColor: C.bg,
    color: C.text,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
    fontSize: 14,
  },
  librarySongsList: {
    maxHeight: 360,
  },
  librarySongsListContent: {
    paddingBottom: 4,
  },
  librarySongRow: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    backgroundColor: C.bg,
    minHeight: 52,
    paddingHorizontal: 12,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  librarySongRowSelected: {
    borderColor: C.accent,
    backgroundColor: '#1f153e',
  },
  librarySongMeta: {
    flex: 1,
    paddingRight: 10,
  },
  librarySongTitle: {
    color: C.text,
    fontSize: 14,
    fontWeight: '700',
  },
  librarySongArtist: {
    marginTop: 2,
    color: C.textMute,
    fontSize: 12,
  },
  librarySongsLoading: {
    paddingVertical: 24,
    alignItems: 'center',
  },
  librarySongsEmpty: {
    paddingVertical: 24,
    alignItems: 'center',
  },
  librarySongsEmptyText: {
    color: C.textDim,
    fontSize: 13,
    textAlign: 'center',
  },
  modalPrimaryButton: {
    marginTop: 8,
    borderRadius: 8,
    backgroundColor: C.accent,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  modalPrimaryButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
});

export default styles;
